version: '3.4'

services:

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: src/Clients/BlazorWebApp/WebApp/Dockerfile

  web.apigateway:
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: src/ApiGateways/WebApiGateway/Web.ApiGateway/Dockerfile

  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: src/Services/OrderService/OrderService.Api/Dockerfile

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: src/Services/NotificationService/NotificationService/Dockerfile

  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService.Api/Dockerfile

  catalogservice.api:
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    build:
      context: .
      dockerfile: src/Services/CatalogService/CatalogService.Api/Dockerfile

  basketservice.api:
    image: ${DOCKER_REGISTRY-}basketserviceapi
    build:
      context: .
      dockerfile: src/Services/BasketService/BasketService.Api/Dockerfile

  paymentservice.api:
    image: ${DOCKER_REGISTRY-}paymentserviceapi
    build:
      context: .
      dockerfile: src/Services/PaymentService/PaymentService.Api/Dockerfile

  s_redis:
    container_name: c_redis
    image: redis

  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:3-management

  s_sqlserver:
    container_name: c_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest

  s_consul:
    container_name: c_consul
    image: consul